kind: pipeline
name: default

workspace:
  path: /source

steps:
  - name: build-p01-amd64
    image: plugins/docker
    settings:
      username: p01
      password:
        from_secret: P01_DOCKER_PASSWORD
      repo: docker.p01.cc/paperplane-api-base
      tags:
        - ${DRONE_SEMVER##v}
        - latest
      registry: docker.p01.cc
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  - name: build-p01-arm64
    image: plugins/docker
    settings:
      username: p01
      password:
        from_secret: P01_DOCKER_PASSWORD
      repo: docker.p01.cc/paperplane-api-base
      platform: linux/arm64
      tags:
        - ${DRONE_SEMVER##v}
        - latest
      registry: docker.p01.cc
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  - name: build-official-amd64
    image: plugins/docker
    settings:
      username: paperplanecc
      password:
        from_secret: DOCKER_PASSWORD
      repo: paperplanecc/paperplane-api-base
      tags:
        - ${DRONE_SEMVER##v}
        - latest

  - name: build-official-arm64
    image: plugins/docker
    settings:
      username: paperplanecc
      password:
        from_secret: DOCKER_PASSWORD
      repo: paperplanecc/paperplane-api-base
      platform: linux/arm64
      tags:
        - ${DRONE_SEMVER##v}
        - latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  - name: push-readme-official
    image: chko/docker-pushrm:1
    environment:
      DOCKER_USER: paperplanecc
      DOCKER_PASS:
        from_secret: DOCKER_PASSWORD
      PUSHRM_SHORT: Provide runtime environment support for PaperPlaneAPI.
      PUSHRM_TARGET: docker.io/paperplanecc/paperplane-api-base

trigger:
  event:
    - tag
  branch:
    - master

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
